In [3]:
import pandas as pd
df=pd.read_csv("/content/Zudio_sales_data.csv")

In [4]:
df.describe()

,Store Number,Postal Code,Selling Area Size (sq ft),Staff Count,Order ID,Customer ID,Product ID,Price,Quantity,Sales Profit
count,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000,7899.000000
mean,50.666034,419982.374984,1112.077478,11.504747,54920.719965,549440.714521,602.069376,1761.113432,4.519433,3170.671376
std,29.095274,11695.237817,193.239371,5.194722,25894.206850,262418.912565,232.066189,716.269447,2.292373,2141.249886
min,1.000000,400006.000000,800.000000,3.000000,10008.000000,100153.000000,204.000000,499.000000,1.000000,200.400000
25%,25.000000,409841.000000,950.000000,7.000000,33192.000000,318516.500000,398.000000,1136.000000,3.000000,1411.200000
50%,51.000000,419988.000000,1100.000000,12.000000,54873.000000,546012.000000,602.000000,1782.000000,5.000000,2681.600000
75%,76.000000,430258.000000,1300.000000,16.000000,77285.000000,780304.000000,803.500000,2373.000000,7.000000,4570.400000
max,100.000000,439985.000000,1400.000000,20.000000,99999.000000,999858.000000,999.000000,2999.000000,8.000000,9596.800000

In [6]:
df.columns

Index(['Store', 'Country', 'State', 'City', 'Category', 'Clothing Type',
       'Store Number', 'Postal Code', 'Store Type', 'Store Open Date',
       'Selling Area Size (sq ft)', 'Store Manager', 'Manager ID',
       'Store Address', 'Contact Information', 'Operating Hours',
       'Staff Count', 'Parking Availability', 'Security Features', 'Order ID',
       'Order Date', 'Month', 'Customer ID', 'Customer Name', 'Product ID',
       'Price', 'Quantity', 'Sales Profit'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7899 entries, 0 to 7898
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      7899 non-null   object
 1   Country                    7899 non-null   object
 2   State                      7899 non-null   object
 3   City                       7899 non-null   object
 4   Category                   7899 non-null   object
 5   Clothing Type              7899 non-null   object
 6   Store Number               7899 non-null   int64
 7   Postal Code                7899 non-null   int64
 8   Store Type                 7899 non-null   object
 9   Store Open Date            7899 non-null   object
 10  Selling Area Size (sq ft)  7899 non-null   int64
 11  Store Manager              7899 non-null   object
 12  Manager ID                 7899 non-null   object
 13  Store Address              7899 non-null   object
 14  Contact Information        7899 non-null   object
 15  Operating Hours            7899 non-null   object
 16  Staff Count                7899 non-null   int64
 17  Parking Availability       7899 non-null   object
 18  Security Features          5861 non-null   object
 19  Order ID                   7899 non-null   int64
 20  Order Date                 7899 non-null   object
 21  Month                      7899 non-null   object
 22  Customer ID                7899 non-null   int64
 23  Customer Name              7899 non-null   object
 24  Product ID                 7899 non-null   int64
 25  Price                      7899 non-null   int64
 26  Quantity                   7899 non-null   int64
 27  Sales Profit               7899 non-null   float64
dtypes: float64(1), int64(9), object(18)
memory usage: 1.7+ MB

In [8]:
df.dtypes

Store                         object
Country                       object
State                         object
City                          object
Category                      object
Clothing Type                 object
Store Number                   int64
Postal Code                    int64
Store Type                    object
Store Open Date               object
Selling Area Size (sq ft)      int64
Store Manager                 object
Manager ID                    object
Store Address                 object
Contact Information           object
Operating Hours               object
Staff Count                    int64
Parking Availability          object
Security Features             object
Order ID                       int64
Order Date                    object
Month                         object
Customer ID                    int64
Customer Name                 object
Product ID                     int64
Price                          int64
Quantity                       int64
Sales Profit                 float64
dtype: object

In [9]:
df.index

RangeIndex(start=0, stop=7899, step=1)

In [10]:
df.isnull().sum()

Store                           0
Country                         0
State                           0
City                            0
Category                        0
Clothing Type                   0
Store Number                    0
Postal Code                     0
Store Type                      0
Store Open Date                 0
Selling Area Size (sq ft)       0
Store Manager                   0
Manager ID                      0
Store Address                   0
Contact Information             0
Operating Hours                 0
Staff Count                     0
Parking Availability            0
Security Features            2038
Order ID                        0
Order Date                      0
Month                           0
Customer ID                     0
Customer Name                   0
Product ID                      0
Price                           0
Quantity                        0
Sales Profit                    0
dtype: int64

In [11]:
df["State"].unique()

array(['Karnataka', 'Gujarat', 'Uttar Pradesh', 'West Bengal',
       'Maharashtra', 'Tamil Nadu', 'Rajasthan', 'Delhi'], dtype=object)

In [12]:
df["State"].value_counts(normalize=True)

State
Rajasthan        0.128244
Uttar Pradesh    0.127991
Delhi            0.127991
Gujarat          0.124320
West Bengal      0.124320
Maharashtra      0.123433
Karnataka        0.121914
Tamil Nadu       0.121788
Name: proportion, dtype: float64

In [13]:
df.head(1000)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
0,Zudio,India,Karnataka,Jalna,Women,Dresses,30,411084,Owned,2022-06-04,...,Alarm,88240,2024-11-06,November,233084,Michele Ochoa,354,1958,5,3916.0
1,Zudio,India,Gujarat,Patna,Kids,Skirts,48,404562,Owned,2020-12-19,...,Alarm,78145,2024-06-17,June,926472,Daniel Jimenez,741,2078,1,831.2
2,Zudio,India,Uttar Pradesh,Kolkata,Men,Hoodies,97,437773,Rented,2023-09-04,...,CCTV,33363,2024-08-17,August,853255,Steven Davis,607,1445,2,1156.0
3,Zudio,India,West Bengal,Kolkata,Women,Dresses,93,431725,Owned,2024-04-11,...,CCTV,46682,2024-03-27,March,106146,Derek Orozco,991,2469,6,5925.6
4,Zudio,India,West Bengal,Guwahati,Men,Dresses,51,415370,Owned,2022-05-29,...,"CCTV, Alarm",58242,2024-04-08,April,264070,Victor Arnold,479,1105,6,2652.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Zudio,India,West Bengal,Mumbai,Men,Shoes,18,425719,Rented,2020-10-08,...,Alarm,36195,2024-10-25,October,615409,Joann Evans,647,2664,8,8524.8
996,Zudio,India,Uttar Pradesh,Madurai,Men,Jeans,89,418039,Owned,2022-01-12,...,Alarm,75800,2024-10-18,October,451115,James Lewis,605,2576,3,3091.2
997,Zudio,India,Karnataka,New Delhi,Women,T-shirts,55,403602,Rented,2023-08-19,...,CCTV,63239,2024-08-26,August,675042,Mr. Kevin White,422,1548,4,2476.8
998,Zudio,India,Karnataka,Rajkot,Women,Skirts,49,434478,Owned,2023-11-24,...,CCTV,68745,2024-08-01,August,643874,Rebekah Carrillo,910,1238,5,2476.0
999,Zudio,India,West Bengal,Coimbatore,Women,Shoes,43,419271,Rented,2023-11-15,...,NaN,78027,2024-09-05,September,722471,Seth Branch,957,2619,2,2095.2

In [14]:
df.tail(25)

,Store,Country,State,City,Category,Clothing Type,Store Number,Postal Code,Store Type,Store Open Date,...,Security Features,Order ID,Order Date,Month,Customer ID,Customer Name,Product ID,Price,Quantity,Sales Profit
7874,Zudio,India,Maharashtra,Mumbai,Men,Shirts,54,405963,Rented,2020-10-01,...,Alarm,91405,2024-09-26,September,481723,Tara Mcintosh,596,2259,2,1807.2
7875,Zudio,India,West Bengal,Varanasi,Kids,Dresses,30,406164,Owned,2023-11-06,...,"CCTV, Alarm",16340,2024-04-21,April,971148,Christopher Ellison,379,1100,5,2200.0
7876,Zudio,India,Uttar Pradesh,Rajkot,Men,Tops,59,411173,Owned,2024-09-12,...,CCTV,94288,2024-06-06,June,670735,Misty Walters,825,691,5,1382.0
7877,Zudio,India,Gujarat,Solapur,Kids,Dresses,8,422290,Owned,2022-08-05,...,Alarm,82650,2024-03-05,March,153975,Jill Combs,287,854,6,2049.6
7878,Zudio,India,Uttar Pradesh,Varanasi,Kids,Jeans,27,414864,Owned,2022-03-04,...,CCTV,11304,2024-09-25,September,773997,Sonya Serrano,552,815,1,326.0
7879,Zudio,India,Maharashtra,New Delhi,Women,Jeans,85,431368,Rented,2021-09-11,...,Alarm,51898,2024-09-08,September,338536,Rachel James,734,1669,1,667.6
7880,Zudio,India,Karnataka,Hyderabad,Kids,Pants,62,421275,Owned,2023-06-02,...,Alarm,33952,2024-06-10,June,893023,Jennifer Stanley,276,1343,7,3760.4
7881,Zudio,India,Maharashtra,Indore,Kids,Jackets,50,418809,Owned,2020-08-31,...,"CCTV, Alarm",54519,2024-08-27,August,527871,Luis Thompson,490,1944,3,2332.8
7882,Zudio,India,Uttar Pradesh,Pune,Kids,Sweaters,21,430460,Rented,2020-03-13,...,NaN,63776,2024-09-01,September,794456,Phillip Barron,398,1117,6,2680.8
7883,Zudio,India,Gujarat,Visakhapatnam,Kids,Jeans,43,425986,Owned,2024-06-03,...,CCTV,74446,2024-07-29,July,283116,Shelley Carter,535,2292,4,3667.2
7884,Zudio,India,Delhi,Ranchi,Women,Dresses,2,425303,Rented,2020-02-02,...,Alarm,87800,2024-10-30,October,485491,Jesse Moore,844,2938,2,2350.4
7885,Zudio,India,Tamil Nadu,Bengaluru,Kids,Dresses,69,410350,Rented,2021-04-26,...,CCTV,18574,2024-01-17,January,809925,Thomas Clay,230,1903,2,1522.4
7886,Zudio,India,Uttar Pradesh,Guwahati,Men,Skirts,8,405686,Owned,2022-07-28,...,Alarm,56589,2024-06-21,June,636458,Samantha Short,391,2956,5,5912.0
7887,Zudio,India,Delhi,Lucknow,Kids,Hoodies,43,424534,Owned,2021-05-08,...,NaN,40956,2024-01-13,January,963130,Kristi Barr,882,1210,8,3872.0
7888,Zudio,India,West Bengal,Chandigarh,Men,Shoes,5,406209,Rented,2023-07-28,...,CCTV,90854,2024-11-17,November,819533,Nathaniel Johnson,803,2310,7,6468.0
7889,Zudio,India,Uttar Pradesh,Madurai,Kids,T-shirts,82,429075,Rented,2023-03-08,...,Alarm,50154,2024-05-02,May,158047,Timothy Atkinson,901,1340,7,3752.0
7890,Zudio,India,Maharashtra,Indore,Kids,Shirts,12,402636,Rented,2023-02-12,...,Alarm,65868,2024-05-28,May,193390,Marco Pratt,810,1626,4,2601.6
7891,Zudio,India,Tamil Nadu,Kochi,Men,Dresses,83,431699,Owned,2020-04-25,...,"CCTV, Alarm",24791,2024-03-25,March,465109,Justin Rivera,393,2653,6,6367.2
7892,Zudio,India,Uttar Pradesh,Vadodara,Women,Sweaters,39,403376,Owned,2022-09-07,...,NaN,75845,2024-11-14,November,356017,Justin Diaz,746,1357,6,3256.8
7893,Zudio,India,Rajasthan,Hyderabad,Women,Jackets,96,415258,Rented,2020-04-23,...,"CCTV, Alarm",33083,2024-01-06,January,801703,Bryan Walker,242,2169,6,5205.6
7894,Zudio,India,Uttar Pradesh,Chandigarh,Kids,Jeans,32,431437,Owned,2024-04-24,...,"CCTV, Alarm",39056,2024-09-27,September,591993,Tracey Andrews,262,2838,1,1135.2
7895,Zudio,India,Uttar Pradesh,Aurangabad,Kids,Jackets,52,424643,Owned,2024-02-03,...,Alarm,85486,2024-03-16,March,822244,Linda Wallace,537,1814,2,1451.2
7896,Zudio,India,Tamil Nadu,Pune,Kids,T-shirts,81,412057,Owned,2021-04-11,...,"CCTV, Alarm",78200,2024-12-02,December,268376,Brandon Baker,457,1961,1,784.4
7897,Zudio,India,Delhi,Madurai,Men,Shoes,58,405203,Rented,2022-06-17,...,CCTV,19883,2024-07-29,July,766283,John Lewis,608,1017,8,3254.4
7898,Zudio,India,Gujarat,Bengaluru,Women,Shirts,20,429823,Owned,2023-02-08,...,"CCTV, Alarm",91451,2024-04-08,April,541226,Nicholas Salazar,583,2773,5,5546.0

In [16]:
df.shape

(7899, 28)

In [17]:
df[['State','City']]

              State        City
0         Karnataka       Jalna
1           Gujarat       Patna
2     Uttar Pradesh     Kolkata
3       West Bengal     Kolkata
4       West Bengal    Guwahati
...             ...         ...
7894  Uttar Pradesh  Chandigarh
7895  Uttar Pradesh  Aurangabad
7896     Tamil Nadu        Pune
7897          Delhi     Madurai
7898        Gujarat   Bengaluru

[7899 rows x 2 columns]